Support Trunk
taiki-e/install-action pull request #129
Opened 2023-06-07 21:29 UTC by azzamsa

Fixes #128 

@taiki-e I don't have a clue on where to get the `manifest/trunk.json`

2023-06-08 01:52 UTC, NobodyXu commented
I think it's created using [tools/manifest.sh](https://github.com/taiki-e/install-action/blob/main/tools/manifest.sh)

2023-06-08 01:56 UTC, NobodyXu requested changes

2023-06-08 01:56 UTC, NobodyXu commented on tools/codegen/base/trunk.json
> +  "tag_prefix": "",
```suggestion
  "tag_prefix": "v",
```

2023-06-08 01:56 UTC, NobodyXu commented on tools/codegen/base/trunk.json
> +      "asset_name": "${package}--${rust_target}.zip"
```suggestion
      "asset_name": "${package}-${rust_target}.zip"
```

2023-06-08 01:56 UTC, NobodyXu commented on tools/codegen/base/trunk.json
> +  "platform": {
```suggestion
  "version_range": "latest",
  "platform": {
```

2023-06-08 03:18 UTC, azzamsa commented
it stuck here.

```
⬢ ❯ ./tools/manifest.sh trunk 0.16.0
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/install-action-internal-codegen trunk 0.16.0`
downloading releases of https://github.com/thedodd/trunk from https://api.github.com/repos/thedodd/trunk/releases
update manifest for versions '=0.16.0'
no asset '["trunk-x86_64-unknown-linux-musl.tar.gz"]' for host platform 'x86_64_linux_musl'
downloading https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-apple-darwin.tar.gz for checksum...
```

2023-06-08 04:25 UTC, NobodyXu requested changes

2023-06-08 04:25 UTC, NobodyXu commented on tools/codegen/base/trunk.json
> +    "x86_64_linux_musl": {},
```suggestion
```

trunk only has pre-built artifacts for x86-64

2023-06-08 04:25 UTC, NobodyXu commented on tools/codegen/base/trunk.json
> +    "aarch64_linux_musl": {},
```suggestion
```

same

2023-06-08 04:25 UTC, NobodyXu commented on tools/codegen/base/trunk.json
> +    "aarch64_macos": {}
```suggestion
```

and it also does not have pre-built artifacts for M1/M2

2023-06-08 07:53 UTC, NobodyXu commented on tools/codegen/base/trunk.json
> +  "platform": {
```suggestion
  "platform": {
    "x86_64_linux_gnu": {},
```

2023-06-08 08:17 UTC, NobodyXu commented
@azzamsa trunks pre-built seems to use glibc 2.19

2023-06-08 08:19 UTC, NobodyXu commented
Alpine failed because trunk does not provide x86_64-unknown-linux-musl build.

2023-06-08 08:22 UTC, azzamsa commented
> I think the best way to resolve this is for trunk to provide pre-built artifacts for musl and for install-action to also use musl artifacts on gnu targets.

You mean, we need to convince  (or make a PR) to Trunk to include musl target in the release?

2023-10-13 21:20 UTC, azzamsa commented
I don't think I can make Trunk compile in musl target.

2023-10-13 21:20 UTC, closed without merging

2024-12-25 17:01 UTC, taiki-e commented
musl support is not required...
See [DEVELOPMENT.md](https://github.com/taiki-e/install-action/blob/main/DEVELOPMENT.md#troubleshooting) for how to deal with such an error.

2024-12-25 23:03 UTC, azzamsa commented
Something like this #795