docs troubleshooting
taiki-e/install-action pull request #147
Opened 2023-06-25 22:38 UTC by joshka

- Add cargo-make to supported tools
- docs: add troubleshooting to development.md

2023-06-25 23:03 UTC, joshka commented
Inadvertently still had the changes from #146 in this - I'll clean this up once #146 is merged.

2023-06-26 04:01 UTC, joshka commented
Rebased on main

2023-06-26 04:05 UTC, joshka commented
fixed typo

2023-06-26 04:06 UTC, taiki-e approved these changes
Thanks.

2023-06-26 04:07 UTC, merged

2023-06-26 04:08 UTC, NobodyXu requested changes

2023-06-26 04:08 UTC, NobodyXu commented on DEVELOPMENT.md
> +manifest, and re-run the manifest tool to regenerate the manifest json file. The base manifest
```suggestion
manifest, and re-run the manifest tool `tools/manifest.sh` to regenerate the manifest json file. The base manifest
```

2023-06-26 04:13 UTC, joshka commented on DEVELOPMENT.md
> +manifest, and re-run the manifest tool to regenerate the manifest json file. The base manifest
Done

2023-06-26 04:14 UTC, NobodyXu commented on DEVELOPMENT.md
> +manifest, and re-run the manifest tool to regenerate the manifest json file. The base manifest
Well it's already merged 😂

2023-06-26 04:15 UTC, joshka commented
whoops missed the merge (another PR incoming)