chore(tools): add cargo-auditable
taiki-e/install-action pull request #741
Opened 2024-11-11 02:00 UTC by simonsan

Closes #740

2024-11-11 12:09 UTC, taiki-e requested changes
Thanks!

2024-11-11 12:09 UTC, taiki-e commented on tools/codegen/base/cargo-auditable.json
> +    }
```suggestion
    },
    "aarch64_macos": {}
```

cargo-auditable also provides aarch64 macos binary.

2024-11-11 12:09 UTC, taiki-e commented on tools/codegen/base/cargo-auditable.json
> +  "website": "https://github.com/rustsec/rustsec/tree/HEAD/cargo-audit",
```suggestion
```

(copy-paste error?)

2024-11-11 13:50 UTC, simonsan commented on tools/codegen/base/cargo-auditable.json
> +  "website": "https://github.com/rustsec/rustsec/tree/HEAD/cargo-audit",
Indeed! Thanks!

2024-11-11 13:55 UTC, simonsan commented
Regenerated the manifest, should be ready to go. 👍🏽

2024-11-11 17:22 UTC, taiki-e commented
It seems to be failing in Windows.

https://github.com/taiki-e/install-action/actions/runs/11779914031/job/32809380176?pr=741#step:8:51

```
info: installing cargo-auditable@latest
info: downloading https://github.com/rust-secure-code/cargo-auditable/releases/download/v0.6.4/cargo-auditable-x86_64-pc-windows-msvc.zip
info: verifying sha256 checksum for cargo-auditable-x86_64-pc-windows-msvc.zip
caution: filename not matched:  cargo-auditable-x86_64-pc-windows-msvc/cargo-auditable.exe
```

(I think failures in test-container is an issue that needs to be addressed on my end.)

2024-11-11 17:48 UTC, simonsan commented
Should be fixed with the latest commit, it seems the folder hierarchy is different in the zip than the other one's ...

2024-11-19 18:56 UTC, taiki-e commented
> (I think failures in test-container is an issue that needs to be addressed on my end.)

I found out that this is actually not a problem on our end, but because cargo-auditable does not support --version flag and tries to forward the input to Cargo in all cases.

For example, in the following case, the output shows the version of Cargo, not the version of cargo-auditable itself.

https://github.com/taiki-e/install-action/actions/runs/11790926857/job/32842147226#step:8:72

> ```
> + cargo-auditable auditable --version
> cargo 1.82.0 (8f40fc59f 2024-08-21)
> ```

@simonsan Could you add cargo-auditable to the following branch to address this issue?

https://github.com/taiki-e/install-action/blob/f725b9adf3838dea66890ca9932712709858c409/main.sh#L792-L793

2024-11-19 19:01 UTC, simonsan commented
Added it 👍🏽

2024-11-19 19:42 UTC, taiki-e approved these changes

2024-11-19 19:43 UTC, merged

2024-11-19 19:51 UTC, taiki-e commented
Published in 2.45.0.